-- Do initialization
\cd C:/git/dungeonmaster/dungeonmaster/dungeonmaster.server/sql

\echo ''
\echo ''
\echo ''
\echo ''
\echo '______ _   _ _   _ _____  _____ _____ _   _  ___  ___  ___   _____ _____ ___________ '
\echo '|  _  \\ | | | \\ | |  __ \\|  ___|  _  | \\ | | |  \\/  | / _ \\ /  ___|_   _|  ___| ___ \\'
\echo '| | | | | | |  \\| | |  \\/| |__ | | | |  \\| | | .  . |/ /_\\ \\\\ `--.  | | | |__ | |_/ /'
\echo '| | | | | | | . ` | | __ |  __|| | | | . ` | | |\\/| ||  _  | `--. \\ | | |  __||    /' 
\echo '| |/ /| |_| | |\\  | |_\\ \\| |___\\ \\_/ / |\\  | | |  | || | | |/\\__/ / | | | |___| |\\ \\ '
\echo '|___/  \\___/\\_| \\_/\\____/\\____/ \\___/\\_| \\_/ \\_|  |_/\\_| |_/\\____/  \\_/ \\____/\\_| \\_|'
\echo ''
\echo ''
\echo ''
\echo ''
\echo 'Welcome to the Dungeon Master setup script. This script consists of multiple single scripts executed in a certain order.'

\echo ''
\echo ''
\echo ''
\echo ''
\echo ''
\echo ''
\echo '  ___ _  _ ___ _____ ___   _   _    '
\echo ' |_ _| \\| |_ _|_   _|_ _| /_\\ | |   '
\echo '  | || .` || |  | |  | | / _ \\| |__ '
\echo ' |___|_|\\_|___| |_| |___/_/ \\_\\____|'
\echo '                                    '
\echo ''
\echo 'Running SETUP/initial.sql'
\i SETUP/initial.sql
\echo ''
\echo ''
\echo ''
\echo '   ___ ___ ___   _ _____ ___ '
\echo '  / __| _ \\ __| /_\\_   _| __|'
\echo ' | (__|   / _| / _ \\| | | _| '
\echo '  \\___|_|_\\___/_/ \\_\\_| |___|'
\echo ''
\echo '                                    '
\echo ''
\echo 'Running CREATE/tables_proc.sql'
\i CREATE/tables_proc.sql
\echo ''
\echo ''
\echo ''
\echo '   ___  ____  ___  __  ____   ___ __________'
\echo '  / _ \\/ __ \\/ _ \\/ / / / /  / _ /_  __/ __/'
\echo ' / ___/ /_/ / ___/ /_/ / /__/ __ |/ / / _/  '
\echo '/_/   \\____/_/   \\____/____/_/ |_/_/ /___/  '
\echo '                                    '
\echo ''
\echo 'Running INSERT/insert.sql'
\i INSERT/insert.sql